name: pub

# Pub is not yet ready to release as a user-accessible package.
version: 1.0.0-unreleased

dependencies:
  # Note: Pub's test infrastructure assumes that any dependencies used in tests
  # will be hosted dependencies.
  analyzer: "^0.25.0"
  args: "^0.13.0"
  barback: "^0.15.2"
  compiler_unsupported: "^1.10.0"
  crypto: "^0.9.0"
  glob: "^1.0.0"
  http: "^0.11.0"
  http_multi_server: "^1.0.0"
  http_parser: "^0.0.2"
  http_throttle: "^1.0.0"
  json_rpc_2: "^1.0.0"
  mime: "^0.9.0"
  oauth2: "^0.9.1"
  path: "^1.2.0"
  pool: "^1.0.0"
  pub_semver: "^1.2.0"
  shelf: "^0.5.0"
  shelf_web_socket: "^0.0.1"
  source_span: "^1.0.0"
  stack_trace: "^1.0.0"
  string_scanner: "^0.1.0"
  watcher: "^0.9.2"
  yaml: "^2.0.0"

dev_dependencies:
  scheduled_test: "^0.12.0"
  test: "^0.12.0"

dependency_overrides:
  test:
    git:
      url: https://github.com/dart-lang/test
      ref: 68ca1a2d918de671ca001a4cd2e1ed9546a909dc
